### ISSUE TITLE
How to run the app correctly?

### ISSUE THREAD

**Issue by grotius-cnc** [DjangoReinhard/FalconView#1]
When running in qt the terminal message is :
locale messages found:  false
axisMask: 511	found 9 active axis
QIODevice::read (QFile, "../QtScreen/src/UI/Position.ui"): device not open
Designer: An error has occurred while reading the UI file at line 1, column 0: Premature end of document.
Press <RETURN> to close this window...

**Comment by DjangoReinhard** [comment]
Sorry, another bug.
I fixed it and hope it will do now

**Comment by grotius-cnc** [comment]
Hi,

App now compiles and run's right away !
